# Generated by Django 3.1.4 on 2020-12-23 17:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.CharField(default='WAW', max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('name', models.CharField(default='Airbus A320-100/-200', max_length=50, primary_key=True, serialize=False)),
                ('flight_range', models.FloatField(null=True)),
                ('speed', models.FloatField(null=True)),
                ('max_passenger', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.CharField(default='0', max_length=20, primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.CharField(default='0', max_length=20, primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('departure_time', models.DateTimeField(null=True)),
                ('arrival_time', models.DateTimeField(null=True)),
                ('alternate_airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_alternate_airport', to='OpenSkyProxy.airport')),
                ('arrival_airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_arrival_airport', to='OpenSkyProxy.airport')),
                ('departure_airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_departure_airport', to='OpenSkyProxy.airport')),
            ],
        ),
    ]
