# Generated by Django 3.1.4 on 2020-12-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenSkyProxy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waypoint',
            name='id',
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='name',
            field=models.CharField(default='0', max_length=50, primary_key=True, serialize=False),
        ),
    ]
