# Generated by Django 3.1.4 on 2021-01-09 20:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('OpenSkyProxy', '0002_auto_20201223_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='route',
            field=django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='airport',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='plane',
            name='name',
            field=models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='name',
            field=models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
