# Generated by Django 3.1.4 on 2021-01-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenSkyProxy', '0005_auto_20210111_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='adj',
            field=models.ManyToManyField(blank=True, null=True, related_name='_waypoint_adj_+', to='OpenSkyProxy.Waypoint'),
        ),
    ]
