# Generated by Django 3.1.4 on 2021-01-13 19:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('OpenSkyProxy', '0006_waypoint_adj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
