# Generated by Django 3.1.4 on 2021-01-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenSkyProxy', '0011_auto_20210113_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='adj',
            field=models.ManyToManyField(blank=True, to='OpenSkyProxy.Waypoint'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='adj',
            field=models.ManyToManyField(blank=True, related_name='_waypoint_adj_+', to='OpenSkyProxy.Waypoint'),
        ),
    ]
